import flet as ft

ICON_SIZE = 35
BOX_PADDING = 15
MESSAGE_SPACING = 15
BOX_BORDER_RADIUS = 5
BOX_BORDER = ft.border.all(1, ft.colors.OUTLINE)
TEXT_FONT_SIZE = 20
DESCRIPTION_MAX_LINES = 3

# Warning banner
WARNING_BANNER_TEXT_COLOR = ft.colors.RED
WARNING_BANNER_ICON_COLOR = ft.colors.AMBER
WARNING_BANNER_BG_COLOR = ft.colors.AMBER_100
WARNING_BANNER_ICON = ft.icons.WARNING_AMBER_ROUNDED

# Error banner
ERROR_BANNER_TEXT_COLOR = ft.colors.RED
ERROR_BANNER_ICON_COLOR = ft.colors.RED
ERROR_BANNER_BG_COLOR = ft.colors.AMBER_100
ERROR_BANNER_ICON = ft.icons.ERROR_ROUNDED
