from src.utils import i18n


class Messages(i18n.TranslatableEnum):
    RUN = 'Run'
    STOP = 'Stop'
    COPY = 'Copy'
    HOOK = 'Hook'
    PAYLOAD = 'Payload'
    SEND = 'Send'
    MESSAGE = 'Message'
    CHOOSE_HOOK_TITLE = 'Choose Hook'
    CHOOSE_PAYLOAD_TITLE = 'Choose Payload'
    NETWORK = 'Network'
    PORT = 'Port'
    HOST = 'Host'
    USE_TUNNELLING_SERVICE = 'Use Tunneling Service'
    PUBLIC_URL = 'Public URL'
    OK = 'Ok'
    HOOK_LOADING_ERROR = 'Failed to load hook: {path}'
    PAYLOAD_LOADING_ERROR = 'Failed to load payload: {path}'
    INVALID_PORT_ERROR = 'Invalid port'
    INVALID_HOST_ERROR = 'Invalid host'
    INVALID_PUBLIC_URL_ERROR = 'Invalid public URL'
    PAYLOAD_REQUIRED = 'Payload is required'
    HOOK_REQUIRED = 'Hook is required'
