[hook]
current = "Default HTTP Hook"
directory = "resources\\hooks"

[payload]
current = "IP Stealer"
directory = "resources\\payloads"

[transport]
current = "Default HTTP Transport"
host = "localhost"
port = 4444

[tunneling]
current = "serveo"
use = true
public_url = ""

[graphics]
resolution = [ 1280, 760,]
theme = "dark"
