import flet as ft

# Warning banner
WARNING_BANNER_TEXT_COLOR = ft.colors.RED
WARNING_BANNER_ICON_COLOR = ft.colors.AMBER
WARNING_BANNER_BG_COLOR = ft.colors.AMBER_100
WARNING_BANNER_ICON = ft.icons.WARNING_AMBER_ROUNDED

# Error banner
ERROR_BANNER_TEXT_COLOR = ft.colors.RED
ERROR_BANNER_ICON_COLOR = ft.colors.RED
ERROR_BANNER_BG_COLOR = ft.colors.AMBER_100
ERROR_BANNER_ICON = ft.icons.ERROR_ROUNDED
